[build]
  command = "npm run build"
  publish = "dist"

# Support SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure proper MIME types for JavaScript files
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
